import { BotConfig } from "../types";
import { buildTelegramButtonPayload, compileButtonModel } from "./buttonActions";

export function generateNodeJsCode(config: BotConfig): string {
  const tokenPlaceholder = config.token || "YOUR_TELEGRAM_BOT_TOKEN";
  const telegramButtons = buildTelegramButtonPayload(config);
  const actionModel = telegramButtons.model;
  
  let code = `/**
 * Telegram Bot - ${config.name || "My Custom Bot"}
 * Generated by Telegram Bot Creator & AI Configurator
 * 
 * วิธีการติดตั้ง:
 * 1. ติดตั้ง Node.js ในเครื่องของคุณ (https://nodejs.org)
 * 2. สร้างโฟลเดอร์ใหม่ แล้วเปิด Terminal/Command Prompt ในโฟลเดอร์นั้น
 * 3. พิมพ์คำสั่ง: npm init -y
 * 4. ติดตั้งไลบรารี: npm install telegraf dotenv
 * 5. สร้างไฟล์ชื่อ .env แล้วพิมพ์: BOT_TOKEN=${tokenPlaceholder}
 * 6. บันทึกโค้ดนี้ลงในไฟล์ index.js
 * 7. รันบอทด้วยคำสั่ง: node index.js
 */

const { Telegraf, Markup } = require('telegraf');
require('dotenv').config();

const BOT_TOKEN = process.env.BOT_TOKEN || '${tokenPlaceholder}';

if (!BOT_TOKEN || BOT_TOKEN === 'YOUR_TELEGRAM_BOT_TOKEN') {
  console.error('❌ ข้อผิดพลาด: กรุณากรอก BOT_TOKEN ในไฟล์ .env');
  process.exit(1);
}

const bot = new Telegraf(BOT_TOKEN);

// ระบบบันทึกการทำงานพื้นฐาน
bot.use(async (ctx, next) => {
  const start = Date.now();
  await next();
  const ms = Date.now() - start;
  console.log(\`[LOG] \${ctx.from?.username || 'user'} -> \${ctx.message?.text || '[Media/Action]'} (\${ms}ms)\`);
});
`;

  // BOT (Direct Chat) Features
  if (config.platform === 'bot' || config.platform === 'all') {
    code += `
// ==========================================
// ฟีเจอร์สำหรับบอทแชตส่วนตัว (Direct Chat)
// ==========================================

// คีย์บอร์ดเมนูด่วน
const mainMenu = Markup.keyboard([
${actionModel.replyButtons.map(action => `  [${JSON.stringify(action.label)}]`).join(",\n")}
]).resize();

const inlineMenu = ${JSON.stringify(telegramButtons.inlineMarkup || null)};
const buttonActions = ${JSON.stringify(actionModel.actions)};

// คำสั่ง /start
bot.start((ctx) => {
  ctx.reply(\`${config.botSettings.welcomeMessage.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\`, mainMenu);
  if (inlineMenu) ctx.reply('เมนูใต้ข้อความ:', inlineMenu);
});
`;

    // Keyboard action handlers
    actionModel.replyButtons.forEach(action => {
      code += `
// Stable action ${action.id}
bot.hears(${JSON.stringify(action.label)}, (ctx) => {
  ctx.reply(${JSON.stringify(action.reply || "รับคำสั่งแล้วครับ")});
});
`;
    });

    actionModel.commands.filter(action => action.command !== "start").forEach(action => {
      code += `
bot.command(${JSON.stringify(action.command)}, (ctx) => ctx.reply(${JSON.stringify(action.reply || "รับคำสั่งแล้วครับ")}));
`;
    });

    if (actionModel.inlineButtons.some(action => action.type === "inline_callback")) {
      code += `
bot.on('callback_query', async (ctx) => {
  const callbackData = ctx.callbackQuery?.data || '';
  const action = buttonActions.find(item => item.callbackData === callbackData);
  if (!action) return ctx.answerCbQuery('ปุ่มนี้หมดอายุหรือไม่พบ Action');
  await ctx.answerCbQuery('สำเร็จ');
  const target = action.target ? buttonActions.find(item => item.id === action.target) : null;
  const reply = action.reply || target?.reply;
  if (reply) await ctx.reply(reply, mainMenu);
});
`;
    }

    // Auto Replies
    config.botSettings.autoReplies.forEach(reply => {
      code += `
// ตอบกลับอัตโนมัติเมื่อพบคำว่า "${reply.keyword}"
bot.hears(new RegExp('${reply.keyword}', 'i'), (ctx) => {
  ctx.reply(\`${reply.reply.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\`);
});
`;
    });

    // Dynamic AI Assistant (Simulated fallback or using server-side / Gemini)
    if (config.botSettings.enableAiAssistant) {
      code += `
// บล็อกนี้คือคำแนะนำเมื่อเปิดใช้งาน AI Assistant
// ในโค้ดจริง คุณสามารถเชื่อมต่อกับ @google/genai หรือ OpenAI API
// ตัวอย่างการเชื่อมต่อกับ Gemini API:
/*
const { GoogleGenAI } = require('@google/genai');
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

bot.on('text', async (ctx) => {
  // ข้ามหากเป็นข้อความปุ่มเมนูหรือคำสั่งหลัก
  const text = ctx.message.text;
  if (${JSON.stringify([...actionModel.replyButtons.map(action => action.label), ...config.botSettings.autoReplies.map(r => r.keyword)])}.includes(text)) {
    return;
  }
  
  try {
    ctx.sendChatAction('typing');
    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: text,
      config: {
        systemInstruction: "${config.botSettings.aiPrompt.replace(/"/g, '\\"')}"
      }
    });
    ctx.reply(response.text);
  } catch (err) {
    console.error('AI Error:', err);
    ctx.reply('ขออภัยด้วยครับ ฉันเกิดข้อผิดพลาดในการประมวลผลคำถามของคุณ');
  }
});
*/
`;
    }
  }

  // GROUP Features
  if (config.platform === 'group' || config.platform === 'all') {
    code += `
// ==========================================
// ฟีเจอร์สำหรับกลุ่มแชต (Group Settings)
// ==========================================
`;

    if (config.groupSettings.welcomeNewMember) {
      code += `
// ต้อนรับสมาชิกใหม่เข้ากลุ่ม
bot.on('new_chat_members', (ctx) => {
  const newMembers = ctx.message.new_chat_members;
  newMembers.forEach(member => {
    const name = member.first_name + (member.last_name ? ' ' + member.last_name : '');
    const welcomeText = \`${config.groupSettings.welcomeMessage.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\`.replace('{name}', name);
    ctx.reply(welcomeText);
  });
});
`;
    }

    // Anti-spam warning counter
    if (config.groupSettings.antiSpam.blockLinks || config.groupSettings.antiSpam.blockSwearWords) {
      code += `
// ตัวแปรเก็บจำนวนการแจ้งเตือนพฤติกรรมไม่เหมาะสม (ในหน่วยความจำชั่วคราว)
const userWarnings = {};

// ระบบตรวจสอบสแปมและคำหยาบ
bot.on('text', async (ctx, next) => {
  const text = ctx.message.text;
  const userId = ctx.from.id;
  const username = ctx.from.username ? '@' + ctx.from.username : ctx.from.first_name;
  
  // ตรวจสอบชนิดแชตว่าเป็นกลุ่ม (Group หรือ Supergroup)
  if (ctx.chat.type === 'group' || ctx.chat.type === 'supergroup') {
    let violation = false;
    let reason = '';

    ${config.groupSettings.antiSpam.blockLinks ? `
    // ตรวจสอบลิงก์ (URLs)
    const urlPattern = /(https?:\\/\\/[^\\s]+)/gi;
    if (urlPattern.test(text)) {
      violation = true;
      reason = 'ห้ามโพสต์ลิงก์ภายนอกกลุ่มแชต';
    }
    ` : ''}

    ${config.groupSettings.antiSpam.blockSwearWords ? `
    // ตรวจสอบคำหยาบ (ตัวอย่าง)
    const swearWords = ['ควย', 'เย็ด', 'เหี้ย', 'สัส', 'หน้าหี', 'มึง', 'กู']; // สามารถเพิ่มคำหยาบได้ที่นี่
    const hasSwear = swearWords.some(word => text.includes(word));
    if (hasSwear) {
      violation = true;
      reason = 'กรุณาใช้คำสุภาพในกลุ่มแชต';
    }
    ` : ''}

    if (violation) {
      try {
        // ลบข้อความที่ละเมิดกฎทันที (บอทต้องเป็นแอดมินกลุ่มและมีสิทธิ์ Delete Messages)
        await ctx.deleteMessage();
        
        // บันทึกและคำนวณการแจ้งเตือน
        if (!userWarnings[userId]) userWarnings[userId] = 0;
        userWarnings[userId]++;

        if (userWarnings[userId] >= ${config.groupSettings.antiSpam.warnLimit}) {
          ctx.reply(\`⚠️ สมาชิก \${username} ละเมิดกฎครบ \${userWarnings[userId]}/${config.groupSettings.antiSpam.warnLimit} ครั้ง จึงถูกเตะออกจากกลุ่ม\`);
          // เตะออกจากกลุ่ม (ต้องเป็นแอดมินกลุ่มและมีสิทธิ์ Ban Users)
          await ctx.banChatMember(userId);
          userWarnings[userId] = 0;
        } else {
          ctx.reply(\`⚠️ สมาชิก \${username} ละเมิดกฎกลุ่ม! [สาเหตุ: \${reason}]\\nได้รับการแจ้งเตือนแล้ว \${userWarnings[userId]}/${config.groupSettings.antiSpam.warnLimit} ครั้ง หากครบกำหนดจะถูกลบออกจากกลุ่ม\`);
        }
        return; // หยุดกระบวนการ ไม่ให้ทำงานต่อในส่วนอื่น
      } catch (err) {
        console.error('Anti-Spam Error (อาจเกิดจากบอทไม่มีสิทธิ์แอดมินหรือรันในแชตส่วนตัว):', err.message);
      }
    }
  }
  await next();
});
`;
    }

    // Custom Commands
    config.groupSettings.customCommands.forEach(cmd => {
      const commandName = cmd.command.startsWith("/") ? cmd.command.slice(1) : cmd.command;
      code += `
// คำสั่งพิเศษ /${commandName}
bot.command('${commandName}', (ctx) => {
  ctx.reply(\`${cmd.reply.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\`);
});
`;
    });

    // Auto announcement of rules
    if (config.groupSettings.rulesInterval > 0) {
      code += `
// ส่งกฎกลุ่มอัตโนมัติทุกๆ ${config.groupSettings.rulesInterval} ชั่วโมง
const rulesAnnouncementText = \`${config.groupSettings.rulesAnnouncement.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\`;
setInterval(async () => {
  try {
    // โค้ดนี้จะส่งกฎกลุ่มไปยังแชตที่คุณระบุไว้เมื่อคุณรันโปรแกรม
    // ตัวอย่างการส่งไปยัง Chat ID:
    // await bot.telegram.sendMessage('YOUR_GROUP_CHAT_ID', rulesAnnouncementText);
    console.log('[Scheduler] ส่งกฎกลุ่มระเบียบการเรียบร้อย');
  } catch (err) {
    console.error('Scheduler Error:', err);
  }
}, ${config.groupSettings.rulesInterval} * 60 * 60 * 1000);
`;
    }
  }

  // CHANNEL Features
  if (config.platform === 'channel' || config.platform === 'all') {
    code += `
// ==========================================
// ฟีเจอร์สำหรับแชนแนล/ช่องข่าวสาร (Channel Settings)
// ==========================================

// ฟังก์ชันสำหรับจัดแต่งโพสต์และส่งเข้าแชนแนล
async function sendToChannel(channelId, text) {
  let formattedText = text;
  
  ${config.channelSettings.autoSignature ? `
  // ใส่ลายเซ็นอัตโนมัติ
  formattedText += '\\n\\n' + \`${config.channelSettings.autoSignatureText.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\`;
  ` : ''}

  try {
    await bot.telegram.sendMessage(channelId, formattedText, {
      parse_mode: '${config.channelSettings.enableFormatting === 'None' ? '' : config.channelSettings.enableFormatting}'
    });
    console.log('✅ ส่งโพสต์ไปแชนแนลเรียบร้อย!');
  } catch (err) {
    console.error('❌ ไม่สามารถส่งข้อความไปแชนแนลได้ (โปรดตรวจสอบว่าบอทเป็นแอดมินและรหัสแชนแนลถูกต้อง):', err.message);
  }
}
`;

    if (config.channelSettings.scheduledPosts.length > 0) {
      code += `
// ตัวอย่างแผนงานส่งโพสต์ล่วงหน้า (Scheduled Posts)
const scheduledPosts = [
${config.channelSettings.scheduledPosts.map(p => `  { time: '${p.time}', content: \`${p.content.replace(/`/g, '\\`').replace(/\${/g, '\\${')}\` }`).join(",\n")}
];

// ตรวจสอบเวลาทุกนาทีและโพสต์อัตโนมัติ
setInterval(() => {
  const now = new Date();
  const currentTime = \`\${String(now.getHours()).padStart(2, '0')}:\${String(now.getMinutes()).padStart(2, '0')}\`;
  
  scheduledPosts.forEach(post => {
    if (post.time === currentTime) {
      console.log(\`[Scheduler] ถึงกำหนดเวลาโพสต์ \${post.time} กำลังส่งข้อมูลไปยังแชนแนล...\`);
      // แก้ไข 'YOUR_CHANNEL_USERNAME_OR_ID' เป็นชื่อแชนแนลของคุณ เช่น '@mychannel'
      sendToChannel('YOUR_CHANNEL_USERNAME_OR_ID', post.content);
    }
  });
}, 60000); // เช็กทุก 1 นาที
`;
    }
  }

  // Run the Bot
  code += `
// เริ่มต้นการทำงานของบอทแบบ Polling
bot.launch().then(() => {
  console.log('🤖 บอท Telegram เริ่มต้นทำงานเรียบร้อยแล้ว!');
  console.log('ลองพิมพ์ /start ในบอทเพื่อทดสอบ หรือเพิ่มบอทลงกลุ่ม/แชนแนล');
});

// จัดการการปิดโปรแกรมอย่างปลอดภัย
process.once('SIGINT', () => bot.stop('SIGINT'));
process.once('SIGTERM', () => bot.stop('SIGTERM'));
`;

  return code;
}

export function generatePythonCode(config: BotConfig): string {
  const tokenPlaceholder = config.token || "YOUR_TELEGRAM_BOT_TOKEN";
  const actionModel = compileButtonModel(config);
  
  let code = `"""
Telegram Bot - ${config.name || "My Custom Bot"}
Generated by Telegram Bot Creator & AI Configurator

วิธีการติดตั้ง:
1. ติดตั้ง Python ในเครื่องของคุณ (https://www.python.org)
2. สร้างโฟลเดอร์ใหม่ แล้วเปิด Terminal/Command Prompt ในโฟลเดอร์นั้น
3. ติดตั้งไลบรารี: pip install pyTelegramBotAPI python-dotenv
4. สร้างไฟล์ชื่อ .env แล้วพิมพ์: BOT_TOKEN=${tokenPlaceholder}
5. บันทึกโค้ดนี้ลงในไฟล์ bot.py
6. รันบอทด้วยคำสั่ง: python bot.py
"""

import os
import re
import time
import threading
from datetime import datetime
import telebot
from telebot import types
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv('BOT_TOKEN', '${tokenPlaceholder}')

if not BOT_TOKEN or BOT_TOKEN == 'YOUR_TELEGRAM_BOT_TOKEN':
    print('❌ ข้อผิดพลาด: กรุณากรอก BOT_TOKEN ในไฟล์ .env')
    exit(1)

bot = telebot.TeleBot(BOT_TOKEN)
`;

  // BOT (Direct Chat) Features
  if (config.platform === 'bot' || config.platform === 'all') {
    code += `
# ==========================================
# ฟีเจอร์สำหรับบอทแชตส่วนตัว (Direct Chat)
# ==========================================

# สร้างคีย์บอร์ดลัดด่วน
def get_main_menu():
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
${actionModel.replyButtons.map(action => `    markup.add(types.KeyboardButton(${JSON.stringify(action.label)}))`).join("\n")}
    return markup

def get_inline_menu():
    markup = types.InlineKeyboardMarkup()
${actionModel.inlineButtons.map(action => {
  if (action.type === "url") return `    markup.add(types.InlineKeyboardButton(${JSON.stringify(action.label)}, url=${JSON.stringify(action.url)}))`;
  if (action.type === "web_app") return `    markup.add(types.InlineKeyboardButton(${JSON.stringify(action.label)}, web_app=types.WebAppInfo(${JSON.stringify(action.webAppUrl)})))`;
  return `    markup.add(types.InlineKeyboardButton(${JSON.stringify(action.label)}, callback_data=${JSON.stringify(action.callbackData)}))`;
}).join("\n") || "    pass"}
    return markup

# คำสั่ง /start
@bot.message_handler(commands=['start'])
def send_welcome(message):
    welcome_text = """${config.botSettings.welcomeMessage}"""
    bot.reply_to(message, welcome_text, reply_markup=get_main_menu())
${actionModel.inlineButtons.length ? "    bot.send_message(message.chat.id, 'เมนูใต้ข้อความ:', reply_markup=get_inline_menu())" : ""}
`;

    // Keyboard and auto reply action handlers
    actionModel.replyButtons.forEach(action => {
      code += `
# Stable action ${action.id}
@bot.message_handler(func=lambda msg: (msg.text or '').strip().lower() == ${JSON.stringify(action.label.trim().toLowerCase())})
def handle_${action.id.replace(/[^a-zA-Z0-9_]/g, "_")}(message):
    bot.reply_to(message, ${JSON.stringify(action.reply || "รับคำสั่งแล้วครับ")})
`;
    });

    actionModel.commands.filter(action => action.command !== "start").forEach(action => {
      code += `
@bot.message_handler(commands=[${JSON.stringify(action.command)}])
def command_${action.id.replace(/[^a-zA-Z0-9_]/g, "_")}(message):
    bot.reply_to(message, ${JSON.stringify(action.reply || "รับคำสั่งแล้วครับ")})
`;
    });

    const callbackActions = actionModel.inlineButtons.filter(action => action.type === "inline_callback");
    if (callbackActions.length) {
      code += `
BUTTON_ACTIONS = ${JSON.stringify(Object.fromEntries(callbackActions.map(action => [action.callbackData, action.reply || actionModel.actions.find(target => target.id === action.target)?.reply || "รับคำสั่งแล้วครับ"])))}

@bot.callback_query_handler(func=lambda call: (call.data or '').startswith('jimmy:'))
def handle_button_callback(call):
    reply = BUTTON_ACTIONS.get(call.data)
    if reply is None:
        bot.answer_callback_query(call.id, 'ปุ่มนี้หมดอายุหรือไม่พบ Action')
        return
    bot.answer_callback_query(call.id, 'สำเร็จ')
    bot.send_message(call.message.chat.id, reply, reply_markup=get_main_menu())
`;
    }

    // Auto replies based on keywords
    config.botSettings.autoReplies.forEach(reply => {
      code += `
# ตอบกลับอัตโนมัติเมื่อพบคำสำคัญ "${reply.keyword}"
@bot.message_handler(func=lambda msg: re.search(r'${reply.keyword}', msg.text, re.IGNORECASE) is not None)
def handle_keyword_${config.botSettings.autoReplies.indexOf(reply)}(message):
    bot.reply_to(message, """${reply.reply}""")
`;
    });
  }

  // GROUP Features
  if (config.platform === 'group' || config.platform === 'all') {
    code += `
# ==========================================
# ฟีเจอร์สำหรับกลุ่มแชต (Group Settings)
# ==========================================
`;

    if (config.groupSettings.welcomeNewMember) {
      code += `
# ต้อนรับสมาชิกใหม่เข้ากลุ่ม
@bot.message_handler(content_types=['new_chat_members'])
def welcome_new_members(message):
    welcome_template = """${config.groupSettings.welcomeMessage}"""
    for member in message.new_chat_members:
        name = member.first_name
        if member.last_name:
            name += f" {member.last_name}"
        
        # แทนที่ {name} ด้วยชื่อผู้เข้ากลุ่มจริง
        welcome_text = welcome_template.replace('{name}', name)
        bot.send_message(message.chat.id, welcome_text)
`;
    }

    // Anti-spam configuration
    if (config.groupSettings.antiSpam.blockLinks || config.groupSettings.antiSpam.blockSwearWords) {
      code += `
# ระบบเตือนและตรวจเช็กสแปม
user_warnings = {}

@bot.message_handler(func=lambda msg: msg.chat.type in ['group', 'supergroup'])
def check_group_moderation(message):
    text = message.text or ""
    user_id = message.from_user.id
    username = f"@{message.from_user.username}" if message.from_user.username else message.from_user.first_name
    
    violation = False
    reason = ""

    ${config.groupSettings.antiSpam.blockLinks ? `
    # บล็อกลิงก์
    if re.search(r'https?://\\S+', text):
        violation = True
        reason = "ห้ามโพสต์ลิงก์ภายนอกกลุ่มแชต"
    ` : ''}

    ${config.groupSettings.antiSpam.blockSwearWords ? `
    # ตรวจคำหยาบ
    swear_words = ['ควย', 'เย็ด', 'เหี้ย', 'สัส', 'หน้าหี', 'มึง', 'กู']
    if any(word in text for word in swear_words):
        violation = True
        reason = "กรุณาใช้คำสุภาพในกลุ่มแชต"
    ` : ''}

    if violation:
        try:
            # ลบข้อความทันที
            bot.delete_message(message.chat.id, message.message_id)
            
            # บันทึกประวัติการเตือน
            if user_id not in user_warnings:
                user_warnings[user_id] = 0
            user_warnings[user_id] += 1
            
            if user_warnings[user_id] >= ${config.groupSettings.antiSpam.warnLimit}:
                bot.send_message(message.chat.id, f"⚠️ สมาชิก {username} ละเมิดกฎครบ {user_warnings[user_id]}/${config.groupSettings.antiSpam.warnLimit} ครั้ง จึงถูกเตะออกจากกลุ่ม")
                # ทำการเตะออกจากกลุ่ม
                bot.ban_chat_member(message.chat.id, user_id)
                user_warnings[user_id] = 0
            else:
                bot.send_message(message.chat.id, f"⚠️ สมาชิก {username} ละเมิดกฎกลุ่ม! [สาเหตุ: {reason}]\\nเตือนแล้ว {user_warnings[user_id]}/${config.groupSettings.antiSpam.warnLimit} ครั้ง")
        except Exception as e:
            print(f"เกิดข้อผิดพลาดในการลบ/เตะผู้ใช้: {e}")
`;
    }

    // Custom commands
    config.groupSettings.customCommands.forEach(cmd => {
      const commandName = cmd.command.startsWith("/") ? cmd.command.slice(1) : cmd.command;
      code += `
# คำสั่งพิเศษ /${commandName}
@bot.message_handler(commands=['${commandName}'])
def handle_custom_${commandName}(message):
    bot.reply_to(message, """${cmd.reply}""")
`;
    });

    // Auto announcements Rules
    if (config.groupSettings.rulesInterval > 0) {
      code += `
# ระบบส่งกฎระเบียบของกลุ่มอัตโนมัติ
def schedule_announcement():
    rules_text = """${config.groupSettings.rulesAnnouncement}"""
    while True:
        # กำหนดความถี่ตามชั่วโมง
        time.sleep(${config.groupSettings.rulesInterval} * 3600)
        try:
            # ทำการส่งกฎไปยังกลุ่ม โดยต้องระบุ Chat ID จริงๆ ลงไปแทน
            # bot.send_message('YOUR_GROUP_CHAT_ID', rules_text)
            print("[Scheduler] ส่งกฎกลุ่มระเบียบการเรียบร้อย")
        except Exception as e:
            print(f"Scheduler Error: {e}")

# เริ่มต้นเธรดทำงานในเบื้องหลัง
threading.Thread(target=schedule_announcement, daemon=True).start()
`;
    }
  }

  // CHANNEL Features
  if (config.platform === 'channel' || config.platform === 'all') {
    code += `
# ==========================================
# ฟีเจอร์สำหรับแชนแนล/ช่องข่าวสาร (Channel Settings)
# ==========================================

def send_to_channel(channel_id, text):
    formatted_text = text
    ${config.channelSettings.autoSignature ? `
    # ต่อท้ายเครดิตลายเซ็น
    formatted_text += "\\n\\n" + """${config.channelSettings.autoSignatureText}"""
    ` : ''}
    
    # รูปแบบการใช้ Markdown/HTML
    parse_mode = "${config.channelSettings.enableFormatting === 'None' ? '' : config.channelSettings.enableFormatting}"
    if parse_mode == "None":
        parse_mode = None
        
    try:
        bot.send_message(channel_id, formatted_text, parse_mode=parse_mode)
        print("✅ ส่งโพสต์ไปแชนแนลเรียบร้อย!")
    except Exception as e:
        print(f"❌ ไม่สามารถส่งข้อความไปแชนแนลได้: {e}")
`;

    if (config.channelSettings.scheduledPosts.length > 0) {
      code += `
# แผนงานกำหนดโพสต์ล่วงหน้า
scheduled_posts = [
${config.channelSettings.scheduledPosts.map(p => `    { "time": "${p.time}", "content": """${p.content}""" }`).join(",\n")}
]

def check_scheduled_posts():
    while True:
        now = datetime.now()
        current_time = now.strftime("%H:%M")
        
        for post in scheduled_posts:
            if post["time"] == current_time:
                print(f"[Scheduler] กำลังโพสต์ไปยังแชนแนล ณ เวลา {post['time']}...")
                # ระบุ Chat ID ของช่อง เช่น '@mychannel'
                send_to_channel('YOUR_CHANNEL_USERNAME_OR_ID', post["content"])
                
        time.sleep(60) # เช็กทุกนาที

# เริ่มต้นตัวเช็กเวลา
threading.Thread(target=check_scheduled_posts, daemon=True).start()
`;
    }
  }

  // Polling run
  code += `
if __name__ == '__main__':
    print('🤖 บอท Python เริ่มต้นทำงานเรียบร้อยแล้ว!')
    bot.infinity_polling()
`;

  return code;
}
